# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectro_app.ui'
#
# Created by: PyQt6 UI code generator
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SpectroApp(object):
    def setupUi(self, SpectroApp):
        SpectroApp.setObjectName("SpectroApp")
        SpectroApp.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(SpectroApp)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonLayout = QtWidgets.QVBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.btnDarkRef = QtWidgets.QPushButton(self.centralwidget)
        self.btnDarkRef.setMinimumSize(QtCore.QSize(0, 40))
        self.btnDarkRef.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnDarkRef.setObjectName("btnDarkRef")
        self.buttonLayout.addWidget(self.btnDarkRef)
        self.btnWhiteRef = QtWidgets.QPushButton(self.centralwidget)
        self.btnWhiteRef.setMinimumSize(QtCore.QSize(0, 40))
        self.btnWhiteRef.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnWhiteRef.setObjectName("btnWhiteRef")
        self.buttonLayout.addWidget(self.btnWhiteRef)
        self.btnAttWhiteRef = QtWidgets.QPushButton(self.centralwidget)
        self.btnAttWhiteRef.setMinimumSize(QtCore.QSize(50, 40))
        self.btnAttWhiteRef.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnAttWhiteRef.setObjectName("btnAttWhiteRef")
        self.buttonLayout.addWidget(self.btnAttWhiteRef)
        self.btnMercuryRef = QtWidgets.QPushButton(self.centralwidget)
        self.btnMercuryRef.setMinimumSize(QtCore.QSize(150, 40))
        self.btnMercuryRef.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnMercuryRef.setObjectName("btnMercuryRef")
        self.buttonLayout.addWidget(self.btnMercuryRef)
        self.btnNeonRef = QtWidgets.QPushButton(self.centralwidget)
        self.btnNeonRef.setMinimumSize(QtCore.QSize(198, 40))
        self.btnNeonRef.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnNeonRef.setObjectName("btnNeonRef")
        self.buttonLayout.addWidget(self.btnNeonRef)
        self.btnAimingBeam = QtWidgets.QPushButton(self.centralwidget)
        self.btnAimingBeam.setMinimumSize(QtCore.QSize(150, 40))
        self.btnAimingBeam.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnAimingBeam.setObjectName("btnAimingBeam")
        self.buttonLayout.addWidget(self.btnAimingBeam)
        self.horizontalLayout.addLayout(self.buttonLayout)
        self.plotArea = QtWidgets.QWidget(self.centralwidget)
        self.plotArea.setObjectName("plotArea")
        self.horizontalLayout.addWidget(self.plotArea)
        SpectroApp.setCentralWidget(self.centralwidget)

        self.retranslateUi(SpectroApp)
        QtCore.QMetaObject.connectSlotsByName(SpectroApp)

    def retranslateUi(self, SpectroApp):
        _translate = QtCore.QCoreApplication.translate
        SpectroApp.setWindowTitle(_translate("SpectroApp", "Spectral Client"))
        self.btnDarkRef.setText(_translate("SpectroApp", "Dark Reference"))
        self.btnWhiteRef.setText(_translate("SpectroApp", "White Reference"))
        self.btnAttWhiteRef.setText(_translate("SpectroApp", "Attenuated White Reference"))
        self.btnMercuryRef.setText(_translate("SpectroApp", "Mercury Reference"))
        self.btnNeonRef.setText(_translate("SpectroApp", "Neon Reference"))
        self.btnAimingBeam.setText(_translate("SpectroApp", "Aiming Beam"))